// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CarbonMoonIcon: typeof import('./components/icons/CarbonMoonIcon.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DesktopNavbar: typeof import('./components/ui/DesktopNavbar.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    MobileHeader: typeof import('./components/ui/MobileHeader.vue')['default']
    MobileNavbar: typeof import('./components/ui/MobileNavbar.vue')['default']
    OldFooter: typeof import('./components/OldFooter.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
