// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Blog001: typeof import('./components/content/blog001.md')['default']
    Blog002: typeof import('./components/content/blog002.md')['default']
    Blog003: typeof import('./components/content/blog003.md')['default']
    Blog004: typeof import('./components/content/blog004.md')['default']
    Blog005: typeof import('./components/content/blog005.md')['default']
    BlogWrapper: typeof import('./components/ui/BlogWrapper.vue')['default']
    DesktopFooter: typeof import('./components/ui/DesktopFooter.vue')['default']
    Header: typeof import('./components/ui/Header.vue')['default']
    Lab002: typeof import('./components/content/lab002.md')['default']
    Lab003: typeof import('./components/content/lab003.md')['default']
    Lab004: typeof import('./components/content/lab004.md')['default']
    Lab004b: typeof import('./components/content/lab004b.md')['default']
    Lab005: typeof import('./components/content/lab005.md')['default']
    Lab005b: typeof import('./components/content/lab005b.md')['default']
    Lab006: typeof import('./components/content/lab006.md')['default']
    Lab007: typeof import('./components/content/lab007.md')['default']
    Lab008: typeof import('./components/content/lab008.md')['default']
    Links: typeof import('./components/content/links.md')['default']
    MobileNavbar: typeof import('./components/ui/MobileNavbar.vue')['default']
    Modal: typeof import('./components/ui/Modal.vue')['default']
    Notes: typeof import('./components/content/notes.md')['default']
    OldFooter: typeof import('./components/OldFooter.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Template: typeof import('./components/content/template.md')['default']
    TheTemplate: typeof import('./components/templates/theTemplate.vue')['default']
  }
}
